added logger

diff --git a/bin/gcpm b/bin/gcpm
--- a/bin/gcpm
+++ b/bin/gcpm
@@ -23,9 +23,10 @@ head_info=gcp
 bucket="" # e.g. gs://gcpm-condor (must be unique in entire GCP)
 admin="" # e.g. admin@example.com
 owner="" # e.g. CondorOwner
+log_level=INFO
 
-params=(max max_cores prefix core mem image preemptible off_timer zones tag reuse interval head_info bucket admin owner)
-params_no_empty=(max_cores prefix core mem image head_info bucket admin owner)
+PARAMS=(max max_cores prefix core mem image preemptible off_timer zones tag reuse interval head_info bucket admin owner log_level)
+PARAMS_NO_EMPTY=(max_cores prefix core mem image head_info bucket admin owner log_level)
 
 # Other variables
 pool_password=""
@@ -33,13 +34,86 @@ edit=0
 
 # HELP
 HELP=$(cat << EOF
-Usage: gcpm [-h] [-f <config file>] [-p <pool_passwrd file>] [-e]
-   -p  <pool_password_file>   Pool file management
+Usage: gcpm [-h] [-f <config file>]  [-l <log level>] [-p <pool_passwrd file>] [-e]
    -f  <config file>          Set config file
+   -l  <log level>            Set log level
+   -p  <pool_password_file>   Pool file management
    -e                         Edit config file
    -h                         print this help
 EOF
 )
+
+# Logger
+LOGGER_LEVELS=("DEBUG" "INFO" "NOTICE" "WARNING" "ERROR")
+LOGGER_COLORS=(3 "" 36 33 31)
+get_log_level () {
+  if [ $# -eq 0 ];then
+    local level=1
+  else
+    local level=$1
+  fi
+  if ! ((level+1)) >& /dev/null;then
+    local i=0
+    while [[ $i -lt ${#LOGGER_LEVELS[@]} ]];do
+      if [[ "$level" = "${LOGGER_LEVELS[$i]}" ]];then
+        level=$i
+        break
+      fi
+      ((i++))
+    done
+  fi
+  echo $level
+}
+
+logger () {
+  local level=$1
+  shift
+  local level_n=$(get_log_level "$level")
+  if [ "$level_n" -lt "$log_level_n" ];then
+    return
+  fi
+  local color=${LOGGER_COLORS[$level_n]}
+  local msg="$*"
+  out=1
+  print_cmd="printf"
+  if [[ $level = "ERROR" ]];then
+    out=2
+    print_cmd=">&2 printf"
+  fi
+  if test  -t $out;then
+    eval "$print_cmd \"\\e[${color}m[$(date '%Y/%m/%d %H:%M:%S')][$level] $msg\\e[m\\n\""
+  else
+    eval "$print_cmd \"[$(date '%Y/%m/%d %H:%M:%S')][$level] $msg\\n\""
+  fi
+}
+
+debug () {
+  logger DEBUG "$*"
+}
+
+info () {
+  logger INFO "$*"
+}
+
+notice () {
+  logger NOTICE "$*"
+}
+
+warn () {
+  logger WARNING "$*"
+}
+
+err () {
+  logger ERROR "$*"
+}
+
+cmd_exec () {
+  info "$ $*"
+  if [ "$log_level_n" -lt 2 ];then
+    out=">/dev/null"
+  fi
+  eval "$* $out"
+}
 
 # Check arguments
 while [ $# -gt 0 ];do
@@ -53,15 +127,15 @@ while [ $# -gt 0 ];do
     shift
     pool_password="$1"
     if [ -z "$pool_password" ];then
-      echo "pool_password file is empty"
+      err "pool_password file is empty"
       exit 1
     fi
   elif [ "$1" = "-e" ];then
     edit=1
   else
-    echo "Unknown arguments: $*"
-    echo ""
-    echo "$HELP"
+    err "Unknown arguments: $*
+
+$HELP"
     exit 1
   fi
   shift
@@ -82,7 +156,7 @@ if ! type gcloud >& /dev/null;then
       curl https://sdk.cloud.google.com | bash
       break
     elif [ "$_s_read" = "n" ];then
-      echo "Intall gcloud: https://cloud.google.com/sdk/install"
+      err "Intall gcloud: https://cloud.google.com/sdk/install"
       exit 1
     fi
   done
@@ -90,15 +164,13 @@ fi
 
 # Functions: Show setup
 show_setup () {
-  echo ""
-  echo "================================================================================"
-  echo "$(date): parameters updated"
-  echo "Configuration file: $CONFIG_FILE"
-  for p in ${params[@]};do
-    eval "echo \$p = \${$p[@]}"
-  done
-  echo "================================================================================"
-  echo ""
+  info "
+================================================================================
+$(date): parameters updated
+Configuration file: $CONFIG_FILE
+$(for p in "${PARAMS[@]}";do eval "echo \$p = \${$p[@]}";done)
+================================================================================
+"
 }
 
 # Functions: Read config function
@@ -120,7 +192,7 @@ check_var () {
   if [ $is_num -eq 1 ];then
     for v in ${var[@]};do
       if ! ((n+1)) 2>&1;then
-        echo "ERROR: $v must be number, $1 is not allowed for $name. Check your configuration file."
+        err "must be number, $1 is not allowed for $name. Check your configuration file."
         exit 1
       fi
     done
@@ -129,7 +201,7 @@ check_var () {
   if [ $no_empty -eq 1 ];then
     for v in ${var[@]};do
       if [ -z "$v" ];then
-        echo "ERROR: $name must not be empty. Check your configuration file."
+        err "$name must not be empty. Check your configuration file."
         exit 1
       fi
     done
@@ -226,10 +298,13 @@ read_config () {
         check_var admin "$var" 0 1
       elif [ "$name" = "owner" ];then
         check_var owner "$var" 0 1
+      elif [ "$name" = "log_level" ];then
+        check_var log_level "$var" 0 1
+        log_level_n=$(get_log_level "$log_level")
       fi
     done < "$CONFIG_FILE"
   else
-    echo "Configuration file:$CONFIG_FILE doesn't exist"
+    err "Configuration file:$CONFIG_FILE doesn't exist"
     esit 1
   fi
 
@@ -239,23 +314,23 @@ read_config () {
   fi
  
   # check variables
-  for v in "${params_no_empty[@]}";do
+  for v in "${PARAMS_NO_EMPTY[@]}";do
     if [ -z "$(eval "echo \$$v")" ];then
-      echo "$v must not be empty"
+      err "$v must not be empty"
       exit 1
     fi
   done
 
   if [ ${#core[@]} -gt ${#max[@]} ];then
-    echo "core and max have different number of definitions"
+    err "core and max have different number of definitions"
     exit 1
   fi
   if [ ${#core[@]} -gt ${#mem[@]} ];then
-    echo "core and memory have different number of definitions"
+    err "core and memory have different number of definitions"
     exit 1
   fi
   if [ ${#core[@]} -gt ${#image[@]} ];then
-    echo "core and image have different number of definitions"
+    err "core and image have different number of definitions"
     exit 1
   fi
 
@@ -318,15 +393,13 @@ if [ -n "$pool_password" ];then
   if ! gsutil ls | grep "${bucket}$" >/dev/null;then
     z=${zone#*=}
     z=${z%-*}
-    echo $ gsutil mb -c coldline -l $z $bucket
-    gsutil mb -c coldline -l $z $bucket
+    cmd_exec "sutil mb -c coldline -l $z $bucket"
     ret=$?
     if [ $ret -ne 0 ];then
       exit $ret
     fi
   fi
-  echo $ gsutil cp "$pool_password" "${bucket}"
-  gsutil cp "$pool_password" "${bucket}"
+  cmd_exec "gsutil cp $pool_password ${bucket}"
   ret=$?
   exit $ret
 fi
@@ -338,7 +411,7 @@ update_wns () {
   ips=()
 
   # Get running instances
-  while read line;do
+  while read -r line;do
     instance=($line)
     name=${instance[0]}
     state=${instance[((${#instance[@]}-1))]}
@@ -348,8 +421,8 @@ update_wns () {
       ip=${instance[((${#instance[@]}-2))]}
     fi
     if [ "$state" == "RUNNING" ];then
-      names=(${names[@]} ${name})
-      ips=(${ips[@]} ${ip})
+      names=("${names[@]}" "${name}")
+      ips=("${ips[@]}" "${ip}")
     fi
   done < <(eval gcloud compute instances list $filter|grep "^$prefix")
 
@@ -363,8 +436,7 @@ update_wns () {
         names=("${names[@]}" "${wn}")
         ips=("${ips[@]}" "${ip}")
       else
-        date
-        echo "WARNIING: $wn is listed in the status, but not listed in $WN_LIST nor gcp pool"
+        warn "$wn is listed in the status, but not listed in $WN_LIST nor gcp pool"
       fi
     fi
   done
@@ -391,16 +463,13 @@ update_wns
 # Functions: Clean up worker nodes
 clean_wns () {
   # Delete instances not in condor_status, which were removed by condor_off
-  local in_status="$(condor_status -autoformat Name|cut -d"." -f1)"
+  local in_status=("$(condor_status -autoformat Name|cut -d"." -f1)")
   local is_deleted=0
   while read -r line;do
     instance=($line)
     name=${instance[0]}
-    if [[ "$in_status" != *${name}* ]];then
-      date
-      echo "$ gcloud compute instances delete ${name} $zone"
-      echo y|gcloud compute instances delete "${name}" "$zone"
-      echo ""
+    if [[ "${in_status[*]}" != *${name}* ]];then
+      cmd_exec "echo y|gcloud compute instances delete ${name} $zone"
       is_deleted=1
     fi
   done < <(eval gcloud compute instances list $filter|grep "^$prefix")
@@ -436,10 +505,7 @@ while :;do
         add=1
         terminated=("${terminated[@]}" "${name}")
       else
-        date
-        echo "$ gcloud compute instances delete ${name} $zone"
-        echo y|gcloud compute instances delete "${name}" "$zone"
-        echo ""
+        cmd_exec "echo y|gcloud compute instances delete ${name} $zone"
         # Update worker node information
         update_wns
       fi
@@ -471,9 +537,7 @@ while :;do
       for instance in "${terminated[@]}";do
         if [[ $instance == ${prefix_core[$i]}* ]];then
           instance_name=$instance
-          date
-          echo "$ gcloud compute start $instance_name"
-          gcloud compute start "$instance_name"
+          cmd_exec "gcloud compute start $instance_name"
           echo ""
         fi
       done
@@ -482,10 +546,8 @@ while :;do
         while [ $n -lt 10000 ];do
           instance_name=${prefix_core[$i]}-$(printf "%04d" $n)
           if ! echo "${all[*]}"|grep -q "$instance_name";then
-            date
             echo "$ gcloud compute instances create $instance_name --metadata-from-file startup-script=${STARTUP_PREFIX}-${core[$i]}core.sh $option --image ${image[$i]}"
-            gcloud compute instances create $instance_name --metadata-from-file startup-script="${STARTUP_PREFIX}-${core[$i]}core.sh" $option --image ${image[$i]}
-            echo ""
+            cmd_exec "gcloud compute instances create $instance_name --metadata-from-file startup-script=\"${STARTUP_PREFIX}-${core[$i]}core.sh\" $option --image ${image[$i]}"
             break
           fi
           instance_name=""
@@ -500,9 +562,7 @@ while :;do
         try=0
         while :;do
           if condor_status |grep -q "$instance_name" ;then
-            date
-            echo "$instance_name is added in the pool"
-            echo
+            info "$instance_name is added in the pool"
             if [[ $max_cores -ne 0 ]];then
               total_cores=$((total_cores+${core[$i]}))
             fi
@@ -510,9 +570,8 @@ while :;do
           fi
           ((try++))
           if [ $try -gt 100 ];then
-            date
-            echo "WARNING: $instance_name is still not available in the condor pool."
-            echo "WARNING: Please check $instance_name status"
+            warn "$instance_name is still not available in the condor pool.
+Please check $instance_name status"
             break
           fi
           sleep 1
