added max_cores

diff --git a/bin/gcpm b/bin/gcpm
--- a/bin/gcpm
+++ b/bin/gcpm
@@ -8,6 +8,7 @@ STARTUP_PREFIX="${CONFIG_DIR}/startup"
 
 # Default parameters
 max=(10)
+max_cores=0 # Set non-zero if you want to limit in total number of cores, instead of each core numbers (ignore "max")
 prefix="gcep-wn"
 core=(1)
 mem=(3750)
@@ -23,8 +24,8 @@ bucket="" # e.g. gs://gcpm-condor (must be unique in entire GCP)
 admin="" # e.g. admin@example.com
 owner="" # e.g. CondorOwner
 
-params=(max prefix core mem image preemptible off_timer zones tag reuse interval head_info bucket admin owner)
-params_no_empty=(max prefix core mem image head_info bucket admin owner)
+params=(max max_cores prefix core mem image preemptible off_timer zones tag reuse interval head_info bucket admin owner)
+params_no_empty=(max_cores prefix core mem image head_info bucket admin owner)
 
 # Other variables
 pool_password=""
@@ -191,9 +192,11 @@ read_config () {
     is_updated=0
     local name
     local var
-    while read name var;do
+    while read -r name var;do
       if [ "$name" = "max" ];then
-        check_var max "$var" 1 1 1
+        check_var max "$var" 1 0 1
+      elif [ "$name" = "max_cores" ];then
+        check_var max_cores "$var" 1 0
       elif [ "$name" = "prefix" ];then
         check_var prefix "$var" 0 1
       elif [ "$name" = "core" ];then
@@ -208,7 +211,7 @@ read_config () {
         check_var off_timer "$var" 1 1
       elif [ "$name" = "zones" ];then
         check_var zones "$var" 0 0
-        zones=$(echo $var|tr , ' ')
+        zones=$(echo "$var"|tr , ' ')
       elif [ "$name" = "tag" ];then
         check_var tag "$var" 0 0
       elif [ "$name" = "reuse" ];then
@@ -236,15 +239,21 @@ read_config () {
   fi
  
   # check variables
-  for v in ${params_no_empty[@]};do
+  for v in "${params_no_empty[@]}";do
     if [ -z "$(eval "echo \$$v")" ];then
       echo "$v must not be empty"
       exit 1
     fi
   done
-  if [ ${#core[@]} -gt ${#max[@]} ];then
-    echo "core and max have different number of definitions"
+  if [[ "$max_cores" -eq 0 && "${#core[@]}" -eq 0 ]];then
+    echo "Set max or max_cores"
     exit 1
+  fi
+  if [ "$max_cores" -eq 0 ];then
+    if [ ${#core[@]} -gt ${#max[@]} ];then
+      echo "core and max have different number of definitions"
+      exit 1
+    fi
   fi
   if [ ${#core[@]} -gt ${#mem[@]} ];then
     echo "core and memory have different number of definitions"
@@ -275,6 +284,12 @@ read_config () {
   fi
   domain=$(hostname -d)
   make_startup
+
+  # make prefix for each core
+  prefix_core=()
+  for((i=0;i<${#core[@]};i++));do
+    prefix_core[$i]=${prefix}-${core[$i]}core
+  done
 
   # Fix bucket
   if [[ ! $bucket =~ gs://* ]];then
@@ -344,14 +359,14 @@ update_wns () {
   done < <(eval gcloud compute instances list $filter|grep "^$prefix")
 
   # Check instance which is not running, but in condor_status (should be in the list until it is removed from the status)
-  in_status=($(condor_status -autoformat Name|cut -d"." -f1))
+  local in_status=($(condor_status -autoformat Name|cut -d"." -f1))
   touch "$WN_LIST"
-  for wn in ${in_status[@]};do
-    if ! echo ${names[@]}|grep -q $wn;then
-      ip=$(grep $wn "$WN_LIST"|cut -d" " -f2)
+  for wn in "${in_status[@]}";do
+    if ! echo " ${names[*]} "|grep -q " $wn ";then
+      ip=$(grep "$wn" "$WN_LIST"|cut -d" " -f2)
       if [ -n "$ip" ];then
-        names=(${names[@]} ${wn})
-        ips=(${ips[@]} ${ip})
+        names=("${names[@]}" "${wn}")
+        ips=("${ips[@]}" "${ip}")
       else
         date
         echo "WARNIING: $wn is listed in the status, but not listed in $WN_LIST nor gcp pool"
@@ -381,15 +396,15 @@ update_wns
 # Functions: Clean up worker nodes
 clean_wns () {
   # Delete instances not in condor_status, which were removed by condor_off
-  in_status="$(condor_status -autoformat Name|cut -d"." -f1)"
-  is_deleted=0
-  while read line;do
+  local in_status="$(condor_status -autoformat Name|cut -d"." -f1)"
+  local is_deleted=0
+  while read -r line;do
     instance=($line)
     name=${instance[0]}
     if [[ "$in_status" != *${name}* ]];then
       date
       echo "$ gcloud compute instances delete ${name} $zone"
-      echo y|gcloud compute instances delete ${name} $zone
+      echo y|gcloud compute instances delete "${name}" "$zone"
       echo ""
       is_deleted=1
     fi
@@ -413,38 +428,60 @@ while :;do
   # Check instances
   all=()
   terminated=()
-  while read line;do
+  if [[ $max_cores -ne 0 ]];then
+    total_cores=0
+  fi
+  while read -r line;do
     instance=($line)
     name=${instance[0]}
     state=${instance[((${#instance[@]}-1))]}
+    add=0
     if [ "$state" == "TERMINATED" ];then
       if [ $reuse -eq 1 ];then
-        all=(${all[@]} ${name})
-        terminated=(${terminated[@]} ${name})
+        add=1
+        terminated=("${terminated[@]}" "${name}")
       else
         date
         echo "$ gcloud compute instances delete ${name} $zone"
-        echo y|gcloud compute instances delete ${name} $zone
+        echo y|gcloud compute instances delete "${name}" "$zone"
         echo ""
         # Update worker node information
         update_wns
       fi
     elif [ "$state" == "RUNNING" ];then
-      all=(${all[@]} ${name})
+      add=1
+    fi
+    if [ $add -eq 1 ];then
+      all=("${all[@]}" "${name}")
+      if [[ $max_cores -ne 0 ]];then
+        for p in "${prefix_core[@]}";do
+          if [[ "$name" == ${p}* ]];then
+            n_core=${p#${prefix}-}
+            n_core=${n_core%core}
+            total_cores=$((total_cores+n_core))
+          fi
+        done
+      fi
     fi
   done < <(eval gcloud compute instances list $filter|grep "^$prefix")
 
   for((i=0;i<${#core[@]};i++));do
-    prefix_core=${prefix}-${core[$i]}core
-    machines="$(condor_status -autoformat Name State|grep $prefix_core)"
-    n_machines=$(echo $(echo "$machines"|wc -l))
+    machines="$(condor_status -autoformat Name State|grep ${prefix_core[$i]})"
     n_unclaimed=$(echo $(echo "$machines"|grep " Unclaimed"|wc -l))
 
-    if [ $n_unclaimed -eq 0 ] && [ $n_machines -lt ${max[$i]} ];then
+    core_check=0
+    if [[ $max_cores -ne 0 ]];then
+      [[ $((total_cores+${core[$i]})) -le $max_cores ]] && core_check=1
+    else
+      n_machines=$(echo "$machines"|wc -l)
+      [[ $n_machines -lt ${max[$i]} ]] && core_check=1
+    fi
+
+    if [[ $n_unclaimed -eq 0 ]] && [[ $core_check -eq 1 ]];then
       # start/create instance
       instance_name=""
       for instance in "${terminated[@]}";do
-        if [[ $instance == ${prefix_core}* ]];then
+        if [[ $instance == ${prefix_core[$i]}* ]];then
           instance_name=$instance
           date
           echo "$ gcloud compute start $instance_name"
@@ -455,7 +492,7 @@ while :;do
       if [ -z "$instance_name" ];then
         n=1
         while [ $n -lt 10000 ];do
-          instance_name=${prefix_core}-$(printf "%04d" $n)
+          instance_name=${prefix_core[$i]}-$(printf "%04d" $n)
           if ! echo ${all[*]}|grep -q $instance_name;then
             date
             echo "$ gcloud compute instances create $instance_name --metadata-from-file startup-script=${STARTUP_PREFIX}-${core[$i]}core.sh $option --image ${image[$i]}"
@@ -478,6 +515,9 @@ while :;do
             date
             echo "$instance_name is added in the pool"
             echo
+            if [[ $max_cores -ne 0 ]];then
+              total_cores=$((total_cores+${core[$i]}))
+            fi
             break
           fi
           ((try++))
