multiple core settings

diff --git a/bin/gcpm b/bin/gcpm
--- a/bin/gcpm
+++ b/bin/gcpm
@@ -4,24 +4,25 @@
 CONFIG_DIR="${HOME}/.config/gcp_condor_pool_manager"
 CONFIG_FILE="${CONFIG_DIR}/config"
 WN_LIST="${CONFIG_DIR}/wn_list"
-STARTUP="${CONFIG_DIR}/startup.sh"
+STARTUP_PREFIX="${CONFIG_DIR}/startup"
 
 # Default parameters
-max=0
+max=(0)
 prefix=""
-core=1
-mem=3000
-image=""
+core=(1)
+mem=(3750)
+image=()
 preemptible=0
 zones=""
 tag=""
 reuse=0
 interval=10
-head_info=hostname
+head_info=gcp
 bucket=""
 admin=""
 owner=""
 params=(max prefix core mem image preemptible zones tag reuse interval head_info bucket admin owner)
+params_no_empty=(max prefix core mem image head_info bucket admin owner)
 
 # Other variables
 pool_password=""
@@ -103,25 +104,40 @@ check_var () {
   local var="$2"
   local is_num="${3:-0}"
   local no_empty="${4:-0}"
+  local array="${4:-0}"
   if [ "$var" = "$(eval "echo \$$name")" ];then
     return 0
   fi
 
+  if [ $array -eq 1 ];then
+    var=(${var//,/ })
+  else
+    var=($var)
+  fi
+
   if [ $is_num -eq 1 ];then
-    if ! expr $var + 1 >/dev/null 2>&1;then
-      echo "ERROR: $var must be number, $var is not allowed. Check your configuration file."
-      exit 1
-    fi
+    for v in ${var[@]};do
+      if ! ((n+1)) 2>&1;then
+        echo "ERROR: $v must be number, $1 is not allowed for $name. Check your configuration file."
+        exit 1
+      fi
+    done
   fi
 
   if [ $no_empty -eq 1 ];then
-    if [ -z "$var" ];then
-      echo "ERROR: $var must not be empty. Check your configuration file."
-      exit 1
-    fi
+    for v in ${var[@]};do
+      if [ -z "$v" ];then
+        echo "ERROR: $name must not be empty. Check your configuration file."
+        exit 1
+      fi
+    done
   fi
 
-  eval "$name=$var"
+  if [ $array -eq 1 ];then
+    eval "$name=(${var[@]})"
+  else
+    eval "$name=${var[0]}"
+  fi
   is_updated=1
 
   return 0
@@ -130,7 +146,9 @@ check_var () {
 make_startup () {
   # Make startup script
 
-  cat << EOF > "${STARTUP}"
+  local i=0
+  while [ $i -lt ${#core[@]} ];do
+    cat << EOF > "${STARTUP}-${core[$i]}core.sh"
 #/bin/bash
 sed -i"" 's/FIXME_ADMIN/${admin}/' /etc/condor/config.d/00_config_local.config
 
@@ -140,8 +158,8 @@ sed -i"" 's/FIXME_DOMAIN/${domain}/' /etc/condor/config.d/10_security.config
 sed -i"" "s/FIXME_PRIVATE_DOMAIN/\${hostname -d}/" /etc/condor/config.d/10_security.config
 
 sed -i"" 's/FIXME_OWNER/${owner}/' /etc/condor/config.d/20_workernode.config
-sed -i"" 's/FIXME_CORE/${core}/' /etc/condor/config.d/20_workernode.config
-sed -i"" 's/FIXME_MEM/${mem}/' /etc/condor/config.d/20_workernode.config
+sed -i"" 's/FIXME_CORE/${core[$i]}/' /etc/condor/config.d/20_workernode.config
+sed -i"" 's/FIXME_MEM/${mem[$i]}/' /etc/condor/config.d/20_workernode.config
 
 gsutil cp "${bucket}/pool_password" /etc/condor/
 chmod 600 /etc/condor/pool_password
@@ -156,6 +174,7 @@ while :;do
   sleep 10
 done
 EOF
+  done
 }
 
 read_config () {
@@ -165,15 +184,15 @@ read_config () {
     local var
     while read name var;do
       if [ "$name" = "max" ];then
-        check_var max "$var" 1 1
+        check_var max "$var" 1 1 1
       elif [ "$name" = "prefix" ];then
         check_var prefix "$var" 0 1
       elif [ "$name" = "core" ];then
-        check_var core "$var" 1 1
+        check_var core "$var" 1 1 1
       elif [ "$name" = "mem" ];then
-        check_var mem "$var" 1 1
+        check_var mem "$var" 1 1 1
       elif [ "$name" = "image" ];then
-        check_var image "$var" 0 1
+        check_var image "$var" 0 1 1
       elif [ "$name" = "preemptible" ];then
         check_var preemptible "$var" 1 1
       elif [ "$name" = "zones" ];then
@@ -200,6 +219,26 @@ read_config () {
     fi
   fi
 
+  # check variables
+  for v in ${params_no_empty[@]};do
+    if [ -z "$(eval "echo \$$v")" ];then
+      echo "$v must not be empty"
+      exit 1
+    fi
+  done
+  if [ ${#core[@]} -gt ${#max[@]} ];then
+    echo "core and max have different number of definitions"
+    exit 1
+  fi
+  if [ ${#core[@]} -gt ${#mem[@]} ];then
+    echo "core and memory have different number of definitions"
+    exit 1
+  fi
+  if [ ${#core[@]} -gt ${#image[@]} ];then
+    echo "core and image have different number of definitions"
+    exit 1
+  fi
+
   # Set head information, and make startup script
   if [ "$head_info" = "hostname" ];then
     head=${HOSTNAME}
@@ -224,9 +263,9 @@ read_config () {
   option=""
   filter=""
   zone=""
-  if [ -n "$image" ];then
-    option="${option} --image $image"
-  fi
+  #if [ -n "$image" ];then
+  #  option="${option} --image $image"
+  #fi
   if [ "$preemptible" -eq 1 ];then
     option="${option} --preemptible"
   fi
@@ -260,18 +299,6 @@ if [ -n "$pool_password" ];then
   exit $ret
 fi
 
-# Check parameters
-
-if [ "$max" -eq 0 ];then
-  echo "ERROR: set non-zero max"
-  exit 1
-fi
-
-if [ -z "$prefix" ];then
-  echo "ERROR: set prefix"
-  exit 2
-fi
-
 # Functions: Update worker node information
 update_wns () {
   # update condor configuration for worker nodes
@@ -295,7 +322,7 @@ update_wns () {
   done < <(eval gcloud compute instances list $filter|grep "^$prefix")
 
   # Check instance which is not running, but in condor_status (should be in the list until it is removed from the status)
-  in_status=($(condor_status -format "%s\n" Name|grep "slot1@${prefix}"|cut -d"@" -f2|cut -d"." -f1))
+  in_status=($(condor_status -autoformat Name|cut -d"." -f1))
   touch "$WN_LIST"
   for wn in ${in_status[@]};do
     if ! echo ${names[@]}|grep -q $wn;then
@@ -325,7 +352,7 @@ update_wns
 # Main loop
 first=1
 while :;do
-  if [ $first -eq 0 ];then  
+  if [ $first -eq 0 ];then
     read_config
   fi
   first=0
@@ -354,58 +381,64 @@ while :;do
     fi
   done < <(eval gcloud compute instances list $filter|grep "^$prefix")
 
-  # Check condor status
-  # 0: "Total", 1: Machines, 2: Owner, 3: Claimed, 4: Unclaimed, 5: Matched, 6: Preempting, 7: Drain
-  #total=($(condor_status -format "%s\n" Name|grep "slot1@${prefix}"|wc -l))
-  total=($(condor_status -total |grep Total))
-  if [ -z "${total[0]}" ] || ( [ ${total[1]} -lt $max ] && [ ${total[4]} -eq 0 ] );then
+  local i=0
+  while [ $i in ${#core[@]} ];do
+    prefix_core=${prefix}-${core[$i]}core
+    machines="$(condor_status -autoformat Name State|grep $prefix_core)"
+    n_machines=$(echo $(echo "$machines"|wc -l))
+    n_unclaimed=$(echo $(echo "$machines"|grep " Unclaimed"|wc -l))
 
-    # start/create instance
-    instance_name=""
-    if [ ${#terminated[@]} -gt 0 ];then
-      instance_name=${terminated[0]}
-      date
-      echo "$ gcloud compute start $instance_name $option"
-      gcloud compute start $instance_name $option
-      echo ""
-    else
-      n=1
-      while [ $n -lt 10000 ];do
-        instance_name=${prefix}-$(printf "%04d" $n)
-        if ! echo ${all[*]}|grep -q $instance_name;then
+    if [ $n_unclaimed -eq 0 ] && [ $n_machines -lt ${max[$i]} ];then
+
+      # start/create instance
+      instance_name=""
+      for instance in "${terminated[@]}";do
+        if [[ $instance == ${prefix_core}* ]];then
+          instance_name=$instance
           date
-          echo "$ gcloud compute instances create $instance_name --metadata-from-file startup-script=$STARTUP $option" 
-          gcloud compute instances create $instance_name --metadata-from-file startup-script="${STARTUP}" $option
+          echo "$ gcloud compute start $instance_name"
+          gcloud compute start $instance_name
           echo ""
-          break
         fi
-        instance_name=""
-        ((n++))
       done
-    fi
-    if [ -n "$instance_name" ];then
-      # Update worker node information
-      update_wns
-      
-      # Check new instance in the pool
-      try=0
-      while [ -z "$(condor_status |grep $instance_name)" ];do
-        if [ -n "$(condor_status |grep $instance_name)" ];then
-          date
-          echo "$instance_name is added in the pool"
-          break
-        fi
-        ((try++))
-        if [ $try -gt 100 ];then
-          date 
-          echo "WARNING: $instance_name is still not available in the condor pool."
-          echo "WARNING: Please check $instance_name status"
-          break
-        fi
-        sleep 1
-      done
-    fi
-  fi
+      if [ -n "$instance_name" ];then
+        n=1
+        while [ $n -lt 10000 ];do
+          instance_name=${prefix_core}-$(printf "%04d" $n)
+          if ! echo ${all[*]}|grep -q $instance_name;then
+            date
+            echo "$ gcloud compute instances create $instance_name --metadata-from-file startup-script=${STARTUP}-${core[$i]}core.sh $option --image ${image[$i]}"
+            gcloud compute instances create $instance_name --metadata-from-file startup-script="${STARTUP}-${core[$i]}core.sh" $option --image ${image[$i]}
+            echo ""
+            break
+          fi
+          instance_name=""
+          ((n++))
+        done
+      fi
+      if [ -n "$instance_name" ];then
+        # Update worker node information
+        update_wns
 
+        # Check new instance in the pool
+        try=0
+        while :;do
+          if [ -n "$(condor_status |grep $instance_name)" ];then
+            date
+            echo "$instance_name is added in the pool"
+            break
+          fi
+          ((try++))
+          if [ $try -gt 100 ];then
+            date
+            echo "WARNING: $instance_name is still not available in the condor pool."
+            echo "WARNING: Please check $instance_name status"
+            break
+          fi
+          sleep 1
+        done
+      fi
+    fi
+  done
   sleep $interval
 done
